version: "3"
services:
  node-app:
   container_name: express-node-app-container
   build: 
    context: .
    target: production
   volumes: 
    - ./src:/app/src:ro
   ports:
    - "4000:4000"
   environment:
    - NODE_ENV=development
   env_file:
    - ./.env
    